### PR TITLE
Implementation on read APIs of controller

### PR DESCRIPTION
**Pull request by angxu**
This PR consists of mostly two parts:
* a parser to parse config data and convert into java beans.
* bean validation logic and testing.

### CODE REVIEW

**Comment by shuzhang1989** [comment]
Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[controller/controller-http/pom.xml, line 39 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep20_FXp6qlStHbXWq:-Kep20_G7zEV1UWFdM45:bv921dp) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/pom.xml#L39)):*
> ```XML
>             <groupId>org.apache.curator</groupId>
>             <artifactId>curator-framework</artifactId>
>             <version>2.9.0</version>
> ```

<version> ${curator.version} </version>?

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java, line 26 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep3AOREZLHuC9hUdpn:-Kep3AOREZLHuC9hUdpo:b-n3eeog) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java#L26)):*
> ```Java
>  * @author Ang Xu (angxu@pinterest.com)
>  */
> public class ControllerConfiguration extends Configuration {
> ```

should we put this into a common module? worker will also likely use this

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java, line 25 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep59S4roN3k47n1CU6:-Kep59S5KIXcIP7slt1R:bv0mkz4) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java#L25)):*
> ```Java
>   MASTER,
>   SLAVE,
>   ANY,
> ```

@newpoo do we allow ANY role? i thought a master must be either master or slave

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/State.java, line 22 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep5N8MsgmwKBcnDw_h:-Kep5N8NxAFiCX2EhwyH:b-jz0qpn) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/State.java#L22)):*
> ```Java
>  * @author Ang Xu (angxu@pinterest.com)
>  */
> public enum State {
> ```

maybe rename to TaskState as more explicit

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java, line 41 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep5ow6vZrdWW95pkdA:-Kep5ow6vZrdWW95pkdB:b-sedoiq) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java#L41)):*
> ```Java
>  * @author Ang Xu (angxu@pinterest.com)
>  */
> public final class ConfigParser {
> ```

this can be a useful thing for tasks too. move into a common module?

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java, line 104 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep7O3UwbceLLQ-IUxN:-Kep7O3UwbceLLQ-IUxO:b-lrixr0) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java#L104)):*
> ```Java
>         .setIp(split[0])
>         .setPort(Integer.valueOf(split[1]))
>         .setAvailabilityZone(split.length == 3 ? split[2] : "unknown");
> ```

make 'unknown' a constant in case we need to reference to it in the future

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by angxu** [comment]
Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java, line 26 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep3AOREZLHuC9hUdpn:-KepA_imP918_W7T6pBE:b67z8b) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java#L26)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

should we put this into a common module? worker will also likely use this
</blockquote></details>

This class is intended to be used by dropwizard only because dropwizard handles all the work of loading and parsing yaml config file and converting it into this class. Others likely won't be able to use it out of the box.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/State.java, line 22 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep5N8MsgmwKBcnDw_h:-KepCC9thLaEh49fnElu:b-7j86r0) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/State.java#L22)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

maybe rename to TaskState as more explicit
</blockquote></details>

sure.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java, line 41 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep5ow6vZrdWW95pkdA:-KepCG2BR6biJzEQaQDb:b-7j86r0) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java#L41)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

this can be a useful thing for tasks too. move into a common module?
</blockquote></details>

sure.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java, line 104 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep7O3UwbceLLQ-IUxN:-KepCHBsowsKfuD_zali:b-kl8g3z) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/config/ConfigParser.java#L104)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

make 'unknown' a constant in case we need to reference to it in the future
</blockquote></details>

good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by shuzhang1989** [comment]
Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java, line 26 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep3AOREZLHuC9hUdpn:-KepNoxOnUnJs07V0Wzf:b-gp5ufu) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerConfiguration.java#L26)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

This class is intended to be used by dropwizard only because dropwizard handles all the work of loading and parsing yaml config file and converting it into this class. Others likely won't be able to use it out of the box.
</blockquote></details>

got it. probably what is more useful is your config parser

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by newpoo** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[controller/controller-http/bin/demo_server.yaml, line 6 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepHnBpZHymDMqLcgto:-KepHnBpZHymDMqLcgtp:b-85lzpf) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/bin/demo_server.yaml#L6)):*
> ```YAML
>       port: 8080
> 
> zkConnectString: observerzookeeper010:2181
> ```

nit: rename zkConnectString to something more accurate?

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerService.java, line 46 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepUbxQ2B3wXjTe1Hiv:-KepUbxQ2B3wXjTe1Hiw:b-8lnh64) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerService.java#L46)):*
> ```Java
>     //TODO(angxu) initialize taskQueue in the right way after implementation is ready
>     TaskQueue taskQueue = new TaskQueue();
>     CuratorFramework zkClient = CuratorFrameworkFactory.newClient(
> ```

Will zkClient reconnect on error?

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java, line 25 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep59S4roN3k47n1CU6:-KepMSxQNrxvHHKPFZ3W:b-r1ocuf) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java#L25)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

@newpoo do we allow ANY role? i thought a master must be either master or slave
</blockquote></details>

Yes, we only support Master or Slave. If the role is not specified in the config file, we treat it as Master.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/SegmentBean.java, line 36 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepMqbEvPVXP96dZUSD:-KepMqbEvPVXP96dZUSE:b65vahf) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/bean/SegmentBean.java#L36)):*
> ```Java
> 
>   @Min(1)
>   /** number of leaf shards */
> ```

nit: let's just call it number of shards.

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/resource/Clusters.java, line 96 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepP3jr_RmR0nK9Fv7g:-KepP3jr_RmR0nK9Fv7h:b-pmgict) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/resource/Clusters.java#L96)):*
>   public List<ClusterBean> getAll() {
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>
>     final Set<String> clusters = taskQueue.getAllClusters();
>     final List<ClusterBean> clusterBeans = new ArrayList<>(clusters.size());
>     try {
>       for (String cluster : clusters) {
>         if (zkClient.checkExists().forPath(zkPath + cluster) == null) {
>           LOG.error("Znode {} doesn't exist. Skipped.", zkPath + cluster);
>           continue;
>         }
>         byte[] data = zkClient.getData().forPath(zkPath + cluster);
>         ClusterBean clusterBean = ConfigParser.parseClusterConfig(cluster, data);
>         if (clusterBean == null) {
>           LOG.error("Failed to parse config for cluster {}. Skipped.", cluster);
>         } else {
>           clusterBeans.add(clusterBean);
>         }
>       }
>     } catch (Exception e) {
>       LOG.error("Failed to read from zookeeper.", e);
>       throw new WebApplicationException(e);
>     }
>     return clusterBeans;
</details>

THere are some identical code in this function and get() above, does it make sense to put them into a private function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by shuzhang1989** [comment]
Review status: 0 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java, line 25 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep59S4roN3k47n1CU6:-KepWx3UIrPtyrkGu1gV:b-tmz9d7) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java#L25)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

Yes, we only support Master or Slave. If the role is not specified in the config file, we treat it as Master.
</blockquote></details>

cool. remove ANY and treat shards without role to be MASTER and update test cases. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by angxu** [comment]
Review status: 0 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java, line 25 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep59S4roN3k47n1CU6:-KepXUbUmwN0ljtTUl9I:brxp9sq) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/Role.java#L25)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

cool. remove ANY and treat shards without role to be MASTER and update test cases. 
</blockquote></details>

Sounds good.

---

*[controller/controller-http/pom.xml, line 39 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-Kep20_FXp6qlStHbXWq:-KepU2Wu0HRt8mJZmiho:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/pom.xml#L39)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

<version> ${curator.version} </version>?
</blockquote></details>

Done.

---

*[controller/controller-http/bin/demo_server.yaml, line 6 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepHnBpZHymDMqLcgto:-KepY6ANGWzfrxuAjhuc:bugflc6) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/bin/demo_server.yaml#L6)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

nit: rename zkConnectString to something more accurate?
</blockquote></details>

Do you have any suggestions? I can't think of one off hand..

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerService.java, line 46 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepUbxQ2B3wXjTe1Hiv:-KepXuoHviedbAu5ZVY0:bs2v9fb) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/ControllerService.java#L46)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

Will zkClient reconnect on error?
</blockquote></details>

The doc says it will be handled automatically:
http://curator.apache.org/curator-framework/index.html

---

*[controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/resource/Clusters.java, line 96 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepP3jr_RmR0nK9Fv7g:-KepXfWUYvEQsujduq06:b-7j86r0) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/src/main/java/com/pinterest/rocksplicator/controller/resource/Clusters.java#L96)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

>   public List<ClusterBean> getAll() {
>     final Set<String> clusters = taskQueue.getAllClusters();
>     final List<ClusterBean> clusterBeans = new ArrayList<>(clusters.size());
>     try {
>       for (String cluster : clusters) {
>         if (zkClient.checkExists().forPath(zkPath + cluster) == null) {
>           LOG.error("Znode {} doesn't exist. Skipped.", zkPath + cluster);
>           continue;
>         }
>         byte[] data = zkClient.getData().forPath(zkPath + cluster);
>         ClusterBean clusterBean = ConfigParser.parseClusterConfig(cluster, data);
>         if (clusterBean == null) {
>           LOG.error("Failed to parse config for cluster {}. Skipped.", cluster);
>         } else {
>           clusterBeans.add(clusterBean);
>         }
>       }
>     } catch (Exception e) {
>       LOG.error("Failed to read from zookeeper.", e);
>       throw new WebApplicationException(e);
>     }
>     return clusterBeans;

THere are some identical code in this function and get() above, does it make sense to put them into a private function?
</blockquote></details>

sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by shuzhang1989** [comment]
Review status: 0 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[controller/controller-http/bin/demo_server.yaml, line 6 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepHnBpZHymDMqLcgto:-KepZ8NJLdIHVnYaMDcS:bgja3ym) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/bin/demo_server.yaml#L6)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

Do you have any suggestions? I can't think of one off hand..
</blockquote></details>

maybe zk endpoints, and each line is an observer. you can refer to our internal zk hosts config: /etc/zookeeper_hosts.conf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by angxu** [comment]
Review status: 0 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/SegmentBean.java, line 36 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepMqbEvPVXP96dZUSD:-Kepb4Y0_3HGTfllK4zL:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-common/src/main/java/com/pinterest/rocksplicator/controller/bean/SegmentBean.java#L36)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

nit: let's just call it number of shards.
</blockquote></details>

Done.

---

*[controller/controller-http/bin/demo_server.yaml, line 6 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-KepHnBpZHymDMqLcgto:-Kepb5ZRh98Iug_OWTV8:bzeyi24) ([raw file](https://github.com/pinterest/rocksplicator/blob/02117c936c3b336b625cc5d4a5a2f603278701c0/controller/controller-http/bin/demo_server.yaml#L6)):*
<details><summary><i>Previously, shuzhang1989 (Shu Zhang) wrote…</i></summary><blockquote>

maybe zk endpoints, and each line is an observer. you can refer to our internal zk hosts config: /etc/zookeeper_hosts.conf
</blockquote></details>

Sure. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by newpoo** [comment]
Reviewed 1 of 30 files at r1, 22 of 28 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by newpoo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-:-Kepy2VXgdh6x4dfQ4s3:bnfp4nl)*

**Comment by shuzhang1989** [comment]
Reviewed 1 of 30 files at r1, 22 of 28 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29)*

**Comment by shuzhang1989** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/29#-:-KeqH0fFTmapicwxDp5W:bnfp4nl)*

**Pull request merged**
