### PR TITLE
Add the rest of the state models for completeness.

### PR DESCRIPTION
**Pull request by rajathprasad**
Adding the following default helix state models to rocksplicator repo
for completeness:
1. LeaderStandby
2. OnlineOffline
3. MasterSlave

### CODE REVIEW

**Comment by newpoo** [comment]
They are helix built-in state models. What's the motivation to add them to our repo?

**Comment by rajathprasad** [comment]
> They are helix built-in state models. What's the motivation to add them to our repo?
For reference and completeness.

**Comment by newpoo** [comment]
How do we keep them consistent with the ones in helix repo? Does it make more sense to use some kind of pointers for reference purpose?

**Comment by rajathprasad** [comment]
> How do we keep them consistent with the ones in helix repo? Does it make more sense to use some kind of pointers for reference purpose?

I couldn't even find the json files in the helix repo. Let me look into this more. Yes, keeping them in sync will be an issue. I'm okay with abandoning this PR in it's current state.

**Pull request closed without merging**
