### PR TITLE
Complete the workerpool framework

### PR DESCRIPTION
**Pull request by shuzhang1989**
Complete the worker pool framework. The diff conatins:
1. Addressing @newpoo 's comments in last diff.
2. Added run script, log 4j config, and assembly.
3. Integrated with task-queue library to fill the holes left in dispatcher.
4. Added a TaskFactory to create Worker task basing on Task POJO.
5. Unit tests. run the worker pool + dispatcher together to verify the behavior is correct.

### CODE REVIEW

**Comment by angxu** [comment]
Looks good overall. 

---

Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 87 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas0nbmZtaKW9uz3h6s:-Kas0nbmZtaKW9uz3h6t:bsszuft) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L87)):*
> ```Java
>           scheduler.schedule(this, dispatcherPollIntervalSec, TimeUnit.SECONDS);
>         } catch (Exception e) {
>           LOG.error("Dispatcher is interrupted!");
> ```

better to log exception as well.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 54 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas2N5snf6m4DIma_Tf:-Kas2N5txrGkQ4xqmvKX:b-t3bw0k) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L54)):*
> ```Java
>    * @throws Exception if there is a running task for the cluster.
>    */
>   public boolean assignTask(TaskBase task) throws Exception {
> ```

It seems it doesn't throw exception anymore. 

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 55 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas2UTOfjs1gbHVqUW2:-Kas2UTOfjs1gbHVqUW3:bhag8uq) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L55)):*
> ```Java
>    */
>   public boolean assignTask(TaskBase task) throws Exception {
>     if (runningTasks.containsKey(task.getCluster())) {
> ```

I know this is already guarded by TaskQueue. But the thread-safe implementation should be:
```
 if (runningTasks.computeIfAbsent(task.getCluster(), k -> new FutureTask(task)) != null) {
  // error
} 
```

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/SleepIncrementTask.java, line 30 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas4eH2SnM6FQai_X26:-Kas4eH2SnM6FQai_X27:berj7m2) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/SleepIncrementTask.java#L30)):*
> ```Java
>  *
>  */
> public final class SleepIncrementTask extends TaskBase<Object> {
> ```

```TaskBase<Integer>```?
```


---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/TaskFactory.java, line 55 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas59GOXs6MBjqh13h5:-Kas59GOXs6MBjqh13h6:b-mc7g5z) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/TaskFactory.java#L55)):*
> ```Java
>       JsonNode taskBody = mapper.readTree(task.body);
>       TaskBase workerTask = (TaskBase) tasks.get(task.name).getConstructor(
>           long.class, String.class, JsonNode.class).newInstance(
> ```

I prefer a builder pattern over reflection because with reflection we'll have to make sure every task type we support has exactly the same constructor signature. But we can refactor it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-:-Kas6063sA7taoAaXUS0:brszc19)*
<!-- Sent from Reviewable.io -->

**Comment by shuzhang1989** [comment]
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 87 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas0nbmZtaKW9uz3h6s:-KaslH6xiVS6Z_GSXhcy:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L87)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

better to log exception as well.
</blockquote></details>

Done.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 54 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas2N5snf6m4DIma_Tf:-KaslGeMN_sScoQGXake:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L54)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

It seems it doesn't throw exception anymore. 
</blockquote></details>

Done.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 55 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas2UTOfjs1gbHVqUW2:-KasmEK054H3Cz0JTj-z:b-1pdjlb) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L55)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

I know this is already guarded by TaskQueue. But the thread-safe implementation should be:
```
 if (runningTasks.computeIfAbsent(task.getCluster(), k -> new FutureTask(task)) != null) {
  // error
} 
```
</blockquote></details>

not sure i fully understand. computeIfAbsent() returns the newly put value which supposed to be not null.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/SleepIncrementTask.java, line 30 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas4eH2SnM6FQai_X26:-KaslFWavj45hlYRyfhU:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/SleepIncrementTask.java#L30)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

```TaskBase<Integer>```?
</blockquote></details>

Done.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/TaskFactory.java, line 55 at r1](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kas59GOXs6MBjqh13h5:-KaslzwW2THs3Vzs33BK:b-ct2lg6) ([raw file](https://github.com/pinterest/rocksplicator/blob/c9729e66354872dab713b1828421d1d9b6b575b2/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/tasks/TaskFactory.java#L55)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

I prefer a builder pattern over reflection because with reflection we'll have to make sure every task type we support has exactly the same constructor signature. But we can refactor it later.
</blockquote></details>

sure, we can do it later. i was assuming tasks all have the same constructor, becuase it's dispatcher who will construct tasks blindly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by newpoo** [comment]
I am taking a look now

**Comment by angxu** [comment]
Reviewed 2 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java, line 99 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat0OZHCtRUABuUCg7Q:-Kat0OZHCtRUABuUCg7R:b-l1vswm) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java#L99)):*
> ```Java
>     dispatcher.start();
>     // Give it enough time for the initialization;
>     Thread.sleep(4900);
> ```

Can we use some more deterministic ways to synchronize than Thread#sleep? You'll be surprised how slow/overloaded sometimes those CI machines are.

---

*[controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java, line 101 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat-Wwz4Mxj23zo2tuk:-Kat-Wwz4Mxj23zo2tul:bsdouv0) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java#L101)):*
> ```Java
>     Thread.sleep(4900);
>     // The test is sometimes flaky, 2 and 3 are both possible
>     Assert.assertTrue(SleepIncrementTask.executionCounter.get() >= 2 &&
> ```

split them into two assert statements. It's easier for us to debug when it fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by newpoo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 68 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat0NNT9-u_7qZB6GCr:-Kat0NNUmCkXLPjS6OAD:b-y9oebo) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L68)):*
> ```Java
>         try {
>           LOG.info("Pulling tasks from DB queue");
>           Task dequeuedTask = taskQueue.dequeueTask(WorkerConfig.getHostName());
> ```

I think we should first acquire the semaphore then dequeue task.

Also we need to try to dequeue as many tasks as possible if we have enough idle workers.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 84 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat2hgVU5vk4E0ji8Ls:-Kat2hgVU5vk4E0ji8Lt:bxniun9) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L84)):*
> ```Java
>       return false;
>     }
>     // An Interrupted exception will be thrown to Task, and onFailure() will be triggered.'
> ```

nit: remove '

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by newpoo** [comment]
I didn't look into test code. The rest looks good to me except the comment for the dispatcher logic.

**Comment by newpoo** [comment]
One more thing, how do you plan to allow a task to ack/fail/ackandEnqueue?

**Comment by shuzhang1989** [comment]
@newpoo good point. there are 2 options now.
1. task implementations can do finish/fail/finishAndEnqueue in their postprocess / onFailure hooks. but this delegates the responsibility to task implementations. To mandate task impls to do it, we can have a default preprocess/postprocess implementation, but tasks can customize it in case it needs to finish and enqueue.
2. do it in TaskBase. It's obvious to call fail() when failed. But for finishAndEnqueue(), it's harder to know. I think we can put the NextChainedTask in the task body and let framework to do the finish / finishAndEnqueue basing on the field. However, if a task needs to enqueue 2 types of chainedtasks basing on some conditions, its not possible here.

**Comment by shuzhang1989** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 68 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat0NNT9-u_7qZB6GCr:-KatG9jjzPoZPOiC-G0T:bt5gm4h) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L68)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

I think we should first acquire the semaphore then dequeue task.

Also we need to try to dequeue as many tasks as possible if we have enough idle workers.
</blockquote></details>

sure. sounds good.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java, line 84 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat2hgVU5vk4E0ji8Ls:-KatElfh1w9SrKBSA2A4:b-896fix) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/WorkerPool.java#L84)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

nit: remove '
</blockquote></details>

Done.

---

*[controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java, line 99 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat0OZHCtRUABuUCg7Q:-KatDM8lHTBe60jNvuQt:b-sbmboj) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java#L99)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

Can we use some more deterministic ways to synchronize than Thread#sleep? You'll be surprised how slow/overloaded sometimes those CI machines are.
</blockquote></details>

sure. we haven't set up CI for java tests. need to set it up later.

---

*[controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java, line 101 at r2](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kat-Wwz4Mxj23zo2tuk:-KatDJyV9OLZGqG6tqsd:b4c9lyr) ([raw file](https://github.com/pinterest/rocksplicator/blob/60a715ff83e0565e37ea3992271e3e4ceed811d0/controller/controller-worker/src/test/java/com/pinterest/rocksplicator/controller/DispatcherTest.java#L101)):*
<details><summary><i>Previously, angxu wrote…</i></summary><blockquote>

split them into two assert statements. It's easier for us to debug when it fails.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by newpoo** [comment]
Another option is to let task to handle all these logics by itself. We just need to provide a handler to task queue to every task. It's the most flexible way. The downside is that every task author should have this knowledge in mind (finish/fail/fainishAndEnqueue accordingly). Given we will have a few people writing tasks, probably it's fine. We can add explicit document to task base to tell people this. What do you think?

**Comment by shuzhang1989** [comment]
sounds reasonable. what you said is similar to option 1 but don't provide any default implementations. we can still provide the hooks as abstract methods, and let task author to decide where to put the logic.

**Comment by angxu** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-:-KaxLfiOVJYBE-kGketQ:bnfp4nl)*

**Comment by newpoo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 86 at r3](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kaxsz2STGqQ27w-78pk:-Kaxsz2STGqQ27w-78pl:b-x01poz) ([raw file](https://github.com/pinterest/rocksplicator/blob/e7ad47ed7cd8c6ec8acb146e653d74465306840b/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L86)):*
> ```Java
>                 break;
>               } else {
>                 if (!workerPool.assignTask(task)) {
> ```

Don't you need to call failTask() here?

I feel the logic can be cleaned up a little bit to make it more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by shuzhang1989** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java, line 86 at r3](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-Kaxsz2STGqQ27w-78pk:-Kaxy3yLkp5h9FHOP75w:blcmrp7) ([raw file](https://github.com/pinterest/rocksplicator/blob/e7ad47ed7cd8c6ec8acb146e653d74465306840b/controller/controller-worker/src/main/java/com/pinterest/rocksplicator/controller/TaskDispatcher.java#L86)):*
<details><summary><i>Previously, newpoo (Bo Liu) wrote…</i></summary><blockquote>

Don't you need to call failTask() here?

I feel the logic can be cleaned up a little bit to make it more readable.
</blockquote></details>

thanks for the suggestion, i did some clean up on the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24)*

**Comment by newpoo** [comment]
:lgtm:

---

Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pinterest/rocksplicator/24#-:-Kay192tbM9UvhatYB6Q:bnfp4nl)*

**Pull request merged**
